class AddIndexesOnDb < ActiveRecord::Migration
  def self.up
    add_index :items, :source_id
    add_index :items, :is_crafted
    add_index :items, :to_list
    add_index :items, :item_level
    add_index :items, :isaugmented
    add_index :sources, :id
    add_index :sources, :description
    add_index :sources, :crafting_allowed
    add_index :price_overrides, :id
    add_index :price_overrides, :item_id
    add_index :price_overrides, :user_id
    add_index :users, :id
    add_index :users, :is_admin
    add_index :creation_codes, :id
    add_index :creation_codes, :creation_code
    add_index :creation_codes, :used
    add_index :competitor_styles, :id
    add_index :competitor_styles, :description
    add_index :crafted_items, :id
    add_index :toon_skill_levels, :id
    add_index :toon_skill_levels, :toon_id
    add_index :toon_skill_levels, :source_id
    add_index :toon_skill_levels, :skill_level
    add_index :toons, :id
    add_index :toons, :name
    add_index :toons, :user_id
    add_index :sales_listings, :updated_at
    add_index :sales_listings, :is_undercut_price
    add_index :sales_listings, :is_tainted
    add_index :wanted_items, :id
    add_index :wanted_items, :item_id
    add_index :wanted_items, :toon_id
    add_index :wanted_items, :is_public
    add_index :competitors, :id
    add_index :competitors, :competitor_style_id
    add_index :competitors, :source_id
    add_index :listing_statuses, :id
    add_index :listing_statuses, :is_final
  end

  def self.down
    remove_index :items, :source_id
    remove_index :items, :is_crafted
    remove_index :items, :to_list
    remove_index :items, :item_level
    remove_index :items, :isaugmented
    remove_index :sources, :id
    remove_index :sources, :description
    remove_index :sources, :crafting_allowed
    remove_index :price_overrides, :id
    remove_index :price_overrides, :item_id
    remove_index :price_overrides, :user_id
    remove_index :users, :id
    remove_index :users, :is_admin
    remove_index :creation_codes, :id
    remove_index :creation_codes, :creation_code
    remove_index :creation_codes, :used
    remove_index :competitor_styles, :id
    remove_index :competitor_styles, :description
    remove_index :crafted_items, :id
    remove_index :toon_skill_levels, :id
    remove_index :toon_skill_levels, :toon_id
    remove_index :toon_skill_levels, :source_id
    remove_index :toon_skill_levels, :skill_level
    remove_index :toons, :id
    remove_index :toons, :name
    remove_index :toons, :user_id
    remove_index :sales_listings, :updated_at
    remove_index :sales_listings, :is_undercut_price
    remove_index :sales_listings, :is_tainted
    remove_index :wanted_items, :id
    remove_index :wanted_items, :item_id
    remove_index :wanted_items, :toon_id
    remove_index :wanted_items, :is_public
    remove_index :competitors, :id
    remove_index :competitors, :competitor_style_id
    remove_index :competitors, :source_id
    remove_index :listing_statuses, :id
    remove_index :listing_statuses, :is_final
  end
end
