require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CreationCodesController do

  # This should return the minimal set of attributes required to create a valid
  # CreationCode. As you add validations to CreationCode, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all creation_codes as @creation_codes" do
      creation_code = CreationCode.create! valid_attributes
      get :index
      assigns(:creation_codes).should eq([creation_code])
    end
  end

  describe "GET show" do
    it "assigns the requested creation_code as @creation_code" do
      creation_code = CreationCode.create! valid_attributes
      get :show, :id => creation_code.id.to_s
      assigns(:creation_code).should eq(creation_code)
    end
  end

  describe "GET new" do
    it "assigns a new creation_code as @creation_code" do
      get :new
      assigns(:creation_code).should be_a_new(CreationCode)
    end
  end

  describe "GET edit" do
    it "assigns the requested creation_code as @creation_code" do
      creation_code = CreationCode.create! valid_attributes
      get :edit, :id => creation_code.id.to_s
      assigns(:creation_code).should eq(creation_code)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CreationCode" do
        expect {
          post :create, :creation_code => valid_attributes
        }.to change(CreationCode, :count).by(1)
      end

      it "assigns a newly created creation_code as @creation_code" do
        post :create, :creation_code => valid_attributes
        assigns(:creation_code).should be_a(CreationCode)
        assigns(:creation_code).should be_persisted
      end

      it "redirects to the created creation_code" do
        post :create, :creation_code => valid_attributes
        response.should redirect_to(CreationCode.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved creation_code as @creation_code" do
        # Trigger the behavior that occurs when invalid params are submitted
        CreationCode.any_instance.stub(:save).and_return(false)
        post :create, :creation_code => {}
        assigns(:creation_code).should be_a_new(CreationCode)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CreationCode.any_instance.stub(:save).and_return(false)
        post :create, :creation_code => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested creation_code" do
        creation_code = CreationCode.create! valid_attributes
        # Assuming there are no other creation_codes in the database, this
        # specifies that the CreationCode created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CreationCode.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => creation_code.id, :creation_code => {'these' => 'params'}
      end

      it "assigns the requested creation_code as @creation_code" do
        creation_code = CreationCode.create! valid_attributes
        put :update, :id => creation_code.id, :creation_code => valid_attributes
        assigns(:creation_code).should eq(creation_code)
      end

      it "redirects to the creation_code" do
        creation_code = CreationCode.create! valid_attributes
        put :update, :id => creation_code.id, :creation_code => valid_attributes
        response.should redirect_to(creation_code)
      end
    end

    describe "with invalid params" do
      it "assigns the creation_code as @creation_code" do
        creation_code = CreationCode.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CreationCode.any_instance.stub(:save).and_return(false)
        put :update, :id => creation_code.id.to_s, :creation_code => {}
        assigns(:creation_code).should eq(creation_code)
      end

      it "re-renders the 'edit' template" do
        creation_code = CreationCode.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CreationCode.any_instance.stub(:save).and_return(false)
        put :update, :id => creation_code.id.to_s, :creation_code => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested creation_code" do
      creation_code = CreationCode.create! valid_attributes
      expect {
        delete :destroy, :id => creation_code.id.to_s
      }.to change(CreationCode, :count).by(-1)
    end

    it "redirects to the creation_codes list" do
      creation_code = CreationCode.create! valid_attributes
      delete :destroy, :id => creation_code.id.to_s
      response.should redirect_to(creation_codes_url)
    end
  end

end
