require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PriceOverridesController do

  # This should return the minimal set of attributes required to create a valid
  # PriceOverride. As you add validations to PriceOverride, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all price_overrides as @price_overrides" do
      price_override = PriceOverride.create! valid_attributes
      get :index
      assigns(:price_overrides).should eq([price_override])
    end
  end

  describe "GET show" do
    it "assigns the requested price_override as @price_override" do
      price_override = PriceOverride.create! valid_attributes
      get :show, :id => price_override.id.to_s
      assigns(:price_override).should eq(price_override)
    end
  end

  describe "GET new" do
    it "assigns a new price_override as @price_override" do
      get :new
      assigns(:price_override).should be_a_new(PriceOverride)
    end
  end

  describe "GET edit" do
    it "assigns the requested price_override as @price_override" do
      price_override = PriceOverride.create! valid_attributes
      get :edit, :id => price_override.id.to_s
      assigns(:price_override).should eq(price_override)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PriceOverride" do
        expect {
          post :create, :price_override => valid_attributes
        }.to change(PriceOverride, :count).by(1)
      end

      it "assigns a newly created price_override as @price_override" do
        post :create, :price_override => valid_attributes
        assigns(:price_override).should be_a(PriceOverride)
        assigns(:price_override).should be_persisted
      end

      it "redirects to the created price_override" do
        post :create, :price_override => valid_attributes
        response.should redirect_to(PriceOverride.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved price_override as @price_override" do
        # Trigger the behavior that occurs when invalid params are submitted
        PriceOverride.any_instance.stub(:save).and_return(false)
        post :create, :price_override => {}
        assigns(:price_override).should be_a_new(PriceOverride)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PriceOverride.any_instance.stub(:save).and_return(false)
        post :create, :price_override => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested price_override" do
        price_override = PriceOverride.create! valid_attributes
        # Assuming there are no other price_overrides in the database, this
        # specifies that the PriceOverride created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PriceOverride.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => price_override.id, :price_override => {'these' => 'params'}
      end

      it "assigns the requested price_override as @price_override" do
        price_override = PriceOverride.create! valid_attributes
        put :update, :id => price_override.id, :price_override => valid_attributes
        assigns(:price_override).should eq(price_override)
      end

      it "redirects to the price_override" do
        price_override = PriceOverride.create! valid_attributes
        put :update, :id => price_override.id, :price_override => valid_attributes
        response.should redirect_to(price_override)
      end
    end

    describe "with invalid params" do
      it "assigns the price_override as @price_override" do
        price_override = PriceOverride.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PriceOverride.any_instance.stub(:save).and_return(false)
        put :update, :id => price_override.id.to_s, :price_override => {}
        assigns(:price_override).should eq(price_override)
      end

      it "re-renders the 'edit' template" do
        price_override = PriceOverride.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PriceOverride.any_instance.stub(:save).and_return(false)
        put :update, :id => price_override.id.to_s, :price_override => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested price_override" do
      price_override = PriceOverride.create! valid_attributes
      expect {
        delete :destroy, :id => price_override.id.to_s
      }.to change(PriceOverride, :count).by(-1)
    end

    it "redirects to the price_overrides list" do
      price_override = PriceOverride.create! valid_attributes
      delete :destroy, :id => price_override.id.to_s
      response.should redirect_to(price_overrides_url)
    end
  end

end
